config/routes.rb
  Rails.application.routes.draw do
    devise_for :users
    root "reviews#top"
    # get 'reviews' => 'reviews#index'
    # get 'reviews/new' =>'reviews#new'
    # post 'reviews'      =>  'reviews#create'
    # delete  'reviews/:id'  => 'reviews#destroy'
    # patch   'reviews/:id'  => 'reviews#update'
    # get   'reviews/:id/edit'  => 'reviews#edit'
    # get  'users/:id'   =>  'users#show'   #Mypageへのルーティング
    # get 'reviews/:id' => 'reviews#show'
    # get 'users/new' => 'users/new'

    # resources :reviews
    resources :shops do
      resources :reviews
      resources :likes, only: [:create, :destroy]
    end

    resources :users, only: [:new, :show]

  end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :shop
  belongs_to :user
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :shops
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :reviews
  belongs_to :user
  belongs_to :place
  has_many :likes

 def like_user(user_id)
   likes.find_by(user_id: user_id)
  end


end

app/models/user.rb
 class User < ActiveRecord::Base
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    has_many :reviews
    has_many :shops
    has_many :likes
  end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end

    def after_sign_in_path_for(resourse)
        user_path(resourse)
    end

    def after_sign_up_path_for(resourse)
        user_path(resourse)
    end

  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, shop_id: params[:shop_id])
    @likes = Like.where(shop_id: params[:shop_id])
    @shops = Shop.all
  end


  def destroy
    like = Like.find_by(user_id: current_user.id, shop_id: params[:shop_id])
    like.destroy
    @likes = Like.where(shop_id: params[:shop_id])
    @shops = Shop.all
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def top
  end

  def index
    @shops = Shop.all
    @shop = Shop.find(params[:shop_id])
    @reviews = @shop.reviews
    @like = @shop.likes.find_by(user_id: current_user.id)

  end

  def new
    @shop = Shop.find(params[:shop_id])
  end

  def create
    Review.create(review_params)
  end

  def destroy
      review = Review.find(params[:id])
      review.destroy if review.user_id == current_user.id
  end

  def edit
      @shop = Shop.find(params[:shop_id])
      @review = Review.find(params[:id])
  end

  def update
      review = Review.find(params[:id])
      if review.user_id == current_user.id
        review.update(review_params)
      end
  end

  def show
    @review = Review.find(params[:id])
  end





  private
  def review_params
    params.permit(:content_text, :shop_id).merge(user_id: current_user.id)
  end

  def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @place = Place.find(params[:place_id])
    @shops = Shop.where(place: params[:place_id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resourse)


  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @nickname = current_user.nickname
      @reviews =current_user.reviews.order("created_at DESC")
      @shops = current_user.shops

  end
end

 def new
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/create.js.erb
("#like-buttons").html("<%= j(render partial: 'like', locals: { like: @like}) %>");

app/views/likes/destroy.js.erb
("#like-buttons").html("<%= j(render partial: 'like', locals: { shops: @shops, likes: @likes }) %>");

app/views/reviews/_like.html.erb
<% if user_signed_in? %>
  <% if shop.like_user(current_user.id) %>
    <%= button_to shop_like_path(shop.id, @like.id), method: :delete, id: "like-button", remote: true do %>
      <i class="fa fa-heart" aria-hidden="true"></i>

    <% end %>
  <% else %>
    <%= button_to shop_likes_path(shop), id: "like-button", remote: true do %>
      <i class="fa fa-heart-o" aria-hidden="true"></i>

    <% end %>
  <% end %>
<% else %>
<i class="fa fa-heart-o" aria-hidden="true"></i>
<% end %>

app/views/reviews/create.html.erb
<div class="contents row">
    <div class="success">
      <h2>
        投稿が完了しました。
      </h2>
      <br>

      <%= link_to "マイページ", user_path(current_user) %>
    </div>
</div>

app/views/reviews/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h2>
        削除が完了しました。
      </h2>
      <section class="to_mypage clearfix">
      <br><%= link_to "マイページ", user_path(current_user) %>
    </section>

    </div>
</div>

app/views/reviews/edit.html.erb
<div class="contents row">
    <%= form_tag("/shops/#{@shop.id}/reviews/#{@review.id}", method: :patch ) do %>
      <h2>
        編集する
      </h2>

      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @review.content_text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
</div>

app/views/reviews/index.html.erb
 <!--<div class="contents clearfix">-->
  <div class="first-content">
    <p class="key-sentence1">地域のひとが</p>
    <p class="key-sentence2">家族になる場所。</p>
  </div>


  <section class="小見出し clearfix">
    <h2><%= @shop.shop_name %></h2>
  </section>
     <div class= "iine clearfix">
    <%= render partial: 'like', locals: { shop: @shop } %>
     </div>
    <section class="address clearfix">
      <h5><%= @shop.address %></h5>
    </section>



  <section class="小見出し clearfix">
    <h2>店舗情報</h2>
   <section class="shop-feature clearfix">
     <div class="details ">
      <h5><%= @shop.shop_info %></h5>
     </div>
   </section>
  </section>



<section class="小見出し clearfix">
  <h2>メニューなど</h2>
  <secstion class="shop-feature clearfix">
    <div class="details">
      　<h5><%= @shop.Menu %></h5>
    </div>
  </section>
</section>

<section class="小見出し clearfix">
  <h2>口コミを見てみよう！</h2>

  <div class="reviews clearfix">
    <% @reviews.each do |review| %>
    <ul class="more_list">
      <% if user_signed_in? && current_user.id == review.user_id %>
      <li>
        <%= link_to '編集', edit_shop_review_path(review.shop.id,review.id), method: :get %>
      </li>
      <li>
        <%= link_to '削除',shop_review_path(review.shop.id,review.id), method: :delete %>
      </li>
      <% end %>
    </ul>
    <h3><%= review.content_text %></h3>
    <span class="name">
        <h3><%= review.user.nickname %></h3>
    </span>
    <% end %>
  </div>
  </section>





  <section class="小見出し clearfix">
    <h2>MAP</h2>
  </section>

    <section class=>
    <img src="https://maps.googleapis.com/maps/api/staticmap?markers=<%= @shop.url_encode %>&size=600x450&key=AIzaSyB1l-vFcIr1wfcU4-Y0i4TFsyQUZTzBkQA" class="mapbox clearfix">

    </section>

app/views/reviews/new.html.erb
<div class="contents_row">
  <%= form_tag("/shops/#{@shop.id}/reviews", method: :post) do %>
    <h2>
      投稿する
    </h2>

    <h2>本文</h2>
    <h2><textarea cols="30" name="content_text"  rows="10"></textarea></h2>
    <h2><input type="submit" ></h2>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class ="contents row">
  <div class="content_post">
    <% if user_signed_in? && current_user.id == @review.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/reviews/#{@review.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/reviews/#{@review.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= @review.content_text %>
    <span class="name">
      <a href="/users/<%= @review.user.id %>">
        <span>投稿者</span><%= @review.user.nickname %>
      </a>
    </span>
  </div>
</div>

app/views/reviews/top.html.erb
    <div class="first-content">
      <p class="key-sentence1">地域のひとが</p>
      <p class="key-sentence2">家族になる場所。</p>
    </div>



    <form action="cgu-bin/example.cgi" method="post" class="search-box ">
      <input type="search" name="search" placeholder="エリア" class="search-area">
      <input type="search" name="search" placeholder="日にち" class="search-date">
      <input type="search" name="search" placeholder="時間" class="search-time">
      <input type="submit" name="submit" value="検索" class="search-button">
    </form>


   <section class="squale-2 clearfix">

          <div class="box1 clearfix">
            <%= image_tag('question-mark.png') %>
            <h1>子ども食堂って？</h1>
          </div>

           <div class="box2 clearfix">
            <%= image_tag('shop-mark.png') %>
            <h1>食堂検索</h1>
           </div>

   </section>

   <section class="小見出し clearfix">
     <h2>子ども食堂とは？</h2>
   </section>

    <section class ="about-child-cafe clearfix">
     <div class="about-chinld-cafe-sentence">

　      <br>「今晩のご飯は僕１人なんだ」
　      <br>「お母さんがお仕事の日はお弁当を買って食べるの」
　      <br>そんなとき、こどもが１人でも入れるのが
        <br>“子ども食堂”
　      <br>栄養満点の温かいごはんをつくって待っているのは、
　      <br>近所のおじさん、おばさん、お姉さん、お兄さんたち。

　　　　 <br>子ども食堂は
　      <br>地域のひとが、家族になる場所です。
        <br>
     </div>
     </section>

    <section class="小見出し clearfix">
      <h2>食堂検索</h2>
    </section>
    <section class="search-list-4 clearfix">

      <div class="Tokyo">

        <%= link_to "東京", shops_path(place_id: 1) %>
      </div>
      <div class="Kanagawa">
        <%= link_to "神奈川", shops_path(place_id: 2)%>
      </div>
      <div class="Chiba">
        <%= link_to "千葉", shops_path(place_id: 3)%>
      </div>

      <div class="Saitama">
         <%= link_to "埼玉", shops_path(place_id: 4)%>
      </div>
    </section>

app/views/reviews/update.html.erb
<div class="contents row">
    <div class="success">
      <h2>
        更新が完了しました。
      </h2>
      <br>
      <%= link_to "マイページ", user_path(current_user) %>
    </div>
</div>

app/views/shops/index.html.erb
    <div class="first-content">
      <p class="key-sentence1">地域のひとが</p>
      <p class="key-sentence2">家族になる場所。</p>
    </div>

    <section class="都道府県一覧 clearfix">
      <h2><%= @place.place %>一覧</h2>
    </section>

<div class="shop-info-in-shoplist clearfix" >
<% @shops.each do |shop| %>
  <h2><%= link_to shop.shop_name, shop_reviews_path(shop.id) %></h2>
   <h2><%= image_tag shop.picture %></h2>
   <h5><%= shop.address %></h5>

<% end %>

</div>

app/views/users/new.html.erb
<header class="header">
    <div class="header__bar row">
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
            </ul>
          </span>
          <a class="post" href="/reviews/new">投稿する</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
    </div>
  </header>

</body>
</html>

app/views/users/show.html.erb
<div class="mypage clearfix" >
  <section class="小見出し clearfix">
      <h2>マイページ</h2>
  </section>

  <section class="小見出し clearfix">
      <h2>お気に入り登録している食堂一覧</h2>


<% if current_user.likes %>
        <% current_user.likes.each do |like| %>
        <div class="shop-info-in-shoplist clearfix" >
           <h2><%= link_to like.shop.shop_name,shop_reviews_path(like.shop.id) %></h2>
           <h2><%= image_tag like.shop.picture %></h2>
          <h6><%= like.shop.address %></h6>
           <h6><%= link_to "口コミ",new_shop_review_path(like.shop.id) %></h6>
        </div>
        <% end %>
<% end %>
</section>
</section>



 <section class="小見出し clearfix">
    <h2><%= @nickname %>さんの口コミ投稿履歴</h2>
  </section>

<div class="reviews clearfix">

    <% @reviews.each do |review| %>

    <ul class="more_list" clearfix>
      <li>
      <% if user_signed_in? && current_user.id == review.user_id %>
      <li>
        <%= link_to '編集', edit_shop_review_path(review.shop.id,review.id), method: :get %>
      </li>
      <li>
        <%= link_to '削除', shop_review_path(review.shop.id,review.id), method: :delete %>
      </li>
      <% end %>
    </ul>
    <h3><%= review.content_text %></h3>
      </a>
    </span>
    <% end %>
  </div>　